In [43]:
import numpy as np
import pandas as pd
from nltk.tokenize import TweetTokenizer
import torch
from word_embeddings import words_to_embeddings, load_embeddings


In [26]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## First we test to see if the functions in word_embeddings.py are working properly. We use a dummy example:

In [27]:
# Basic test to see if load_embeddings are working
embeddings = load_embeddings()
embeddings


{'a': array([1., 2., 3., 1.]),
 'b': array([1., 2., 3., 2.]),
 'c': array([1., 2., 3., 3.]),
 'd': array([1., 2., 3., 4.]),
 'e': array([1., 2., 3., 5.]),
 'f': array([1., 2., 3., 6.]),
 'g': array([1., 2., 3., 7.]),
 'h': array([1., 2., 3., 8.]),
 'i': array([1., 2., 3., 9.]),
 'j': array([ 1.,  2.,  3., 10.]),
 'k': array([ 1.,  2.,  3., 11.]),
 'l': array([ 1.,  2.,  3., 12.]),
 'm': array([ 1.,  2.,  3., 13.]),
 'n': array([ 1.,  2.,  3., 14.]),
 'o': array([ 1.,  2.,  3., 15.]),
 'p': array([ 1.,  2.,  3., 16.]),
 'q': array([ 1.,  2.,  3., 17.]),
 'r': array([ 1.,  2.,  3., 18.]),
 's': array([ 1.,  2.,  3., 19.]),
 't': array([ 1.,  2.,  3., 20.]),
 'u': array([ 1.,  2.,  3., 21.]),
 'v': array([ 1.,  2.,  3., 22.]),
 'w': array([ 1.,  2.,  3., 23.]),
 'x': array([ 1.,  2.,  3., 24.]),
 'y': array([ 1.,  2.,  3., 25.]),
 'z': array([ 1.,  2.,  3., 26.])}

In [28]:
words = ['a', 'c', 'd', 'g', 'i']
words_to_embeddings(words, embeddings)

[array([1., 2., 3., 1.]),
 array([1., 2., 3., 3.]),
 array([1., 2., 3., 4.]),
 array([1., 2., 3., 7.]),
 array([1., 2., 3., 9.])]

It appears that everything is working properly. Next we load the data.

In [56]:
# Load csv and remove columns with nan
df = pd.read_csv("post.csv")
df = df.dropna()
df.reset_index(inplace=True)
df

index  Unnamed: 0                                              Title  \
0         9           9                                 Dear Professors...   
1        14          14                                 Farewell Ann Arbor   
2        17          17                                    HELLO MY FRIEND   
3        18          18  I've been teaching for almost a decade. This i...   
4        20          20         how do i make the war in ukraine about me?   
...     ...         ...                                                ...   
1975   2968        2968                                  EECS 419 Syllabus   
1976   2969        2969                                        Winter FOMO   
1977   2971        2971  Best spot around campus to smoke and chat on a...   
1978   2974        2974      Does someone have an invite on the Faves app?   
1979   2975        2975                Question to chemistry grad students   

                                                   Text  Upvotes  Downvotes  \
0     My grandmother passed away one week ago. You k...      828         16   
1     As I sit here typically this, I have tears com...      732         14   
2     Stephanie, our favorite buddy from Pierpont Pa...      710          7   
3     Edit: Wow. Thank you everyone for all your tho...      703          7   
4     i'm not ukrainian and i don't have any friends...      734         63   
...                                                 ...      ...        ...   
1975   I’m thinking about adding EECS 419 to my sche...        3          2   
1976  Hey Reddit! I am feeling pretty lonely again. ...       18          2   
1977  A girl and I are going out for the first time ...        0          0   
1978  I saw an add on Snapchat about the faves app a...        0          0   
1979  Hi!! \n\nI got accepted into the chemistry PhD...       24          1   

     Subreddit Source  
0         uofm    top  
1         uofm    top  
2         uofm    top  
3         uofm    top  
4         uofm    top  
...        ...    ...  
1975      uofm    new  
1976      uofm    new  
1977      uofm    new  
1978      uofm    new  
1979      uofm    new  

[1980 rows x 8 columns]

In [57]:
# concatenate title and text
df['Title'] = df['Title'].fillna('')
df['Text'] = df['Text'].fillna('')
df['Content'] = df['Title'] + ' ' + df['Text']
df = df.drop(['Title', 'Text'], axis=1)
df

index  Unnamed: 0  Upvotes  Downvotes Subreddit Source  \
0         9           9      828         16      uofm    top   
1        14          14      732         14      uofm    top   
2        17          17      710          7      uofm    top   
3        18          18      703          7      uofm    top   
4        20          20      734         63      uofm    top   
...     ...         ...      ...        ...       ...    ...   
1975   2968        2968        3          2      uofm    new   
1976   2969        2969       18          2      uofm    new   
1977   2971        2971        0          0      uofm    new   
1978   2974        2974        0          0      uofm    new   
1979   2975        2975       24          1      uofm    new   

                                                Content  
0     Dear Professors... My grandmother passed away ...  
1     Farewell Ann Arbor As I sit here typically thi...  
2     HELLO MY FRIEND Stephanie, our favorite buddy ...  
3     I've been teaching for almost a decade. This i...  
4     how do i make the war in ukraine about me? i'm...  
...                                                 ...  
1975  EECS 419 Syllabus  I’m thinking about adding E...  
1976  Winter FOMO Hey Reddit! I am feeling pretty lo...  
1977  Best spot around campus to smoke and chat on a...  
1978  Does someone have an invite on the Faves app? ...  
1979  Question to chemistry grad students Hi!! \n\nI...  

[1980 rows x 7 columns]

In [58]:
# convert to lowercase and tokenize text
tt = TweetTokenizer()
df['Content'] = df['Content'].map(lambda x : tt.tokenize(x.lower()))
df

index  Unnamed: 0  Upvotes  Downvotes Subreddit Source  \
0         9           9      828         16      uofm    top   
1        14          14      732         14      uofm    top   
2        17          17      710          7      uofm    top   
3        18          18      703          7      uofm    top   
4        20          20      734         63      uofm    top   
...     ...         ...      ...        ...       ...    ...   
1975   2968        2968        3          2      uofm    new   
1976   2969        2969       18          2      uofm    new   
1977   2971        2971        0          0      uofm    new   
1978   2974        2974        0          0      uofm    new   
1979   2975        2975       24          1      uofm    new   

                                                Content  
0     [dear, professors, ..., my, grandmother, passe...  
1     [farewell, ann, arbor, as, i, sit, here, typic...  
2     [hello, my, friend, stephanie, ,, our, favorit...  
3     [i've, been, teaching, for, almost, a, decade,...  
4     [how, do, i, make, the, war, in, ukraine, abou...  
...                                                 ...  
1975  [eecs, 419, syllabus, i, ’, m, thinking, about...  
1976  [winter, fomo, hey, reddit, !, i, am, feeling,...  
1977  [best, spot, around, campus, to, smoke, and, c...  
1978  [does, someone, have, an, invite, on, the, fav...  
1979  [question, to, chemistry, grad, students, hi, ...  

[1980 rows x 7 columns]

In [59]:
embeddings = load_embeddings("glove.6B.50d.txt")

In [60]:
df['Word_Embedding'] = df['Content'].map(lambda x : words_to_embeddings(x, embeddings))
df

index  Unnamed: 0  Upvotes  Downvotes Subreddit Source  \
0         9           9      828         16      uofm    top   
1        14          14      732         14      uofm    top   
2        17          17      710          7      uofm    top   
3        18          18      703          7      uofm    top   
4        20          20      734         63      uofm    top   
...     ...         ...      ...        ...       ...    ...   
1975   2968        2968        3          2      uofm    new   
1976   2969        2969       18          2      uofm    new   
1977   2971        2971        0          0      uofm    new   
1978   2974        2974        0          0      uofm    new   
1979   2975        2975       24          1      uofm    new   

                                                Content  \
0     [dear, professors, ..., my, grandmother, passe...   
1     [farewell, ann, arbor, as, i, sit, here, typic...   
2     [hello, my, friend, stephanie, ,, our, favorit...   
3     [i've, been, teaching, for, almost, a, decade,...   
4     [how, do, i, make, the, war, in, ukraine, abou...   
...                                                 ...   
1975  [eecs, 419, syllabus, i, ’, m, thinking, about...   
1976  [winter, fomo, hey, reddit, !, i, am, feeling,...   
1977  [best, spot, around, campus, to, smoke, and, c...   
1978  [does, someone, have, an, invite, on, the, fav...   
1979  [question, to, chemistry, grad, students, hi, ...   

                                         Word_Embedding  
0     [[-0.29946, 1.172, 0.3289, -0.74413, 1.0811, -...  
1     [[0.29064, 1.4114, -1.021, 0.044633, 0.30793, ...  
2     [[-0.38497, 0.80092, 0.064106, -0.28355, -0.02...  
3     [[0.92884, -0.72457, 0.068095, -0.3816, -0.038...  
4     [[0.68938, -0.10644, 0.17083, -0.37583, 0.7517...  
...                                                 ...  
1975  [[-0.99965, -1.1125, 0.1582, -0.32839, -1.0551...  
1976  [[-0.28054, 1.2422, -0.88838, -0.096132, -0.94...  
1977  [[-0.91572, 0.60345, -0.31077, 0.28433, 0.5461...  
1978  [[0.2293, 0.34231, 0.059817, 0.083003, 0.57685...  
1979  [[0.19854, 0.23367, -0.13229, -0.031831, 0.885...  

[1980 rows x 8 columns]